my_string = input('Введите комментарий: ')
print('Количество символов в строке:',len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ' ,'_'))
print(my_string[0])
print(my_string[-1])